name: Deploy app

on:
  push:
    branches:
      - main

jobs:
  clone:
    runs-on: self-hosted

    steps:
      - name: Deploying app
        run: |
          rm -rf /home/laravel/project/T-Caps
          cd /home/laravel/project
          git clone https://github.com/HE-Arc/T-Caps.git
          cd ./T-Caps
          composer install --optimize-autoloader --no-dev
          npm install
          cp ../.env .env
          php artisan key:generate
          php artisan migrate
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          npm run build