name: Deploy app

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: self-hosted

    steps:
      - name: Deploying app
        run: |
          cd /home/laravel/project
          if [ -d "./T-Caps" ]; then
            cd ./T-Caps
            git pull
          else
            git clone https://github.com/HE-Arc/T-Caps.git
            cd ./T-Caps
          fi
          composer install --optimize-autoloader --no-dev
          npm install
          cp ../.env .env
          php artisan key:generate --force
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          npm run build
